version: "3.8"

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: example-backend
    ports:
      - 8080:8080
      - 6379:6379
      - 5432:5432
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db_postgres
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=pswd123
      - POSTGRES_DATABASE=postgres

  redis:
    image: redis
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=pswd123
    container_name: db_postgres
    volumes:
      - ./data:/var/lib/postgresql/data

