version: "3.8"

services:
  backend:
    build: ./ml-kurkkumopo-backend/
    ports: 
      - 5000:5000
    volumes: 
      - model:/src/model
  
  frontend:
    build: ./ml-kurkkumopo-frontend/
    ports: 
      - 3000:3000
    volumes: 
      - model:/src/model
  
  training:
    build: ./ml-kurkkumopo-training/
    volumes:
      - img:/src/img
      - data:/scr/data
      - model:/src/model

volumes:
  img:
  data:
  model: